#!/usr/bin/env python3
"""Generate strings.S: UTF-16LE (CHAR16) string constants for the EFI app.

Emitting UTF-16 string literals from GNU as macros is unreliable (the `'\\c`
char-value idiom collides with escape parsing), so we generate the data table
here instead. Each entry becomes a 2-byte-aligned, NUL-terminated CHAR16 label
in a dedicated section that the linker script places after the code.
"""

import sys

# label -> ASCII text (encoded as UTF-16LE). Use \r\n for EFI console newlines.
STRINGS = {
    "s_banner":      "vibtanium efi self-test: start\r\n",
    "s_pass":        "[PASS] ",
    "s_fail":        "[FAIL] ",
    "s_crlf":        "\r\n",
    "t_add":         "opcode add r=3+4",
    "t_movl":        "opcode movl + cmp.eq",
    "t_chka":        "opcode chk.a.clr fp takes recovery branch",
    "t_conout":      "efi ConOut->OutputString returns SUCCESS",
    "t_setget":      "efi SetVariable/GetVariable round-trip",
    "var_name":      "VibSelfTest",
    "s_result_pass": "VIBTANIUM-SELFTEST-RESULT: ALL PASS\r\n",
    "s_result_fail": "VIBTANIUM-SELFTEST-RESULT: FAILURES\r\n",
}


def emit(out):
    out.write("\t/* Auto-generated by gen_strings.py -- do not edit. */\n")
    out.write("\t.section .rodata,\"a\"\n")
    out.write("\t.align 8\n")
    for label, text in STRINGS.items():
        data = text.encode("utf-16-le") + b"\x00\x00"
        out.write("\t.global %s\n%s:\n" % (label, label))
        # 16 bytes per line for readability.
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            out.write("\t.byte " + ",".join("0x%02x" % b for b in chunk) + "\n")
    out.write("\n")


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "strings.S"
    with open(path, "w", newline="\n") as f:
        emit(f)
    return 0


if __name__ == "__main__":
    sys.exit(main())
